# Generated by Django 4.2.3 on 2024-06-28 02:18

import apps.accounts.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(error_messages={'unique': 'This email is already in use.'}, max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('phone', models.CharField(blank=True, help_text='Must not have any spaces, parentheses, or dashes', max_length=16)),
                ('date_of_birth', models.DateField(blank=True, help_text='Must be formatted as YYYY-MM-DD', null=True)),
                ('company', models.CharField(blank=True, max_length=64)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_token', models.CharField(blank=True, max_length=64)),
                ('avatar', models.ImageField(blank=True, upload_to='avatars')),
                ('is_superuser', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['first_name'],
            },
            managers=[
                ('objects', apps.accounts.managers.AccountManager()),
            ],
        ),
    ]
